import React, { useState } from 'react';
import { Candidate, JobOpening } from '../../types';
import { Field } from '../AccountViews';

interface Props { jobOpenings: JobOpening[]; candidates: Candidate[]; departments: string[]; onAddJobOpening: (job: any) => Promise<boolean>; onAddCandidate: (candidate: any) => Promise<boolean>; onUpdateCandidateStage: (id: string, stage: Candidate['stage']) => Promise<boolean>; onEvaluateCandidateAI: (id: string) => Promise<boolean> }
export default function RecruitmentView({jobOpenings,candidates,departments,onAddJobOpening,onAddCandidate,onUpdateCandidateStage,onEvaluateCandidateAI}: Props) {
  const [jobId,setJobId]=useState('All'), [evaluating,setEvaluating]=useState('');
  async function add(event:React.FormEvent<HTMLFormElement>,kind:'job'|'candidate') {event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));if(await (kind==='job' ? onAddJobOpening({...values,status:'Active'}) : onAddCandidate(values))) form.reset();}
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Recruitment</h1><p className="text-sm text-slate-500 mt-1">Job openings, applicants and hiring stages.</p></div>
    <div className="grid xl:grid-cols-2 gap-6"><details className="account-panel"><summary className="cursor-pointer font-bold">Add a job opening</summary><form onSubmit={event=>void add(event,'job')} className="space-y-4 mt-5"><Field label="Job title"><input name="title" required maxLength={200}/></Field><Field label="Department"><select name="department">{departments.map(dept=><option key={dept}>{dept}</option>)}</select></Field><Field label="Location"><input name="location" required maxLength={200} placeholder="City or remote"/></Field><Field label="Employment type"><select name="type">{['Full-time','Part-time','Contract','Remote'].map(type=><option key={type}>{type}</option>)}</select></Field><button className="account-primary">Save opening</button></form></details>
    <details className="account-panel"><summary className="cursor-pointer font-bold">Add an applicant</summary><form onSubmit={event=>void add(event,'candidate')} className="space-y-4 mt-5"><Field label="Job opening"><select name="jobId" required defaultValue=""><option value="">Choose opening</option>{jobOpenings.filter(job=>job.status==='Active').map(job=><option key={job.id} value={job.id}>{job.title}</option>)}</select></Field><Field label="Full name"><input name="name" required maxLength={200}/></Field><Field label="Email"><input name="email" type="email" required maxLength={254}/></Field><Field label="Phone (optional)"><input name="phone" type="tel" maxLength={80}/></Field><Field label="Resume text (optional)"><textarea name="resumeText" rows={5} maxLength={20000}/></Field><button className="account-primary">Save applicant</button></form></details></div>
    <section className="account-panel space-y-4"><h2 className="font-bold text-lg">Openings ({jobOpenings.length})</h2>{!jobOpenings.length && <p className="text-sm text-slate-500">Create your first opening above.</p>}<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{jobOpenings.map(job=><button key={job.id} onClick={()=>setJobId(job.id)} className="text-left rounded-xl border border-slate-200 dark:border-slate-800 p-4 hover:border-indigo-400"><h3 className="font-semibold">{job.title}</h3><p className="text-xs text-slate-500 mt-2">{job.department} · {job.location} · {job.type}</p><p className="text-xs text-indigo-600 mt-2">{job.applicantsCount} applicants · {job.status}</p></button>)}</div></section>
    <section className="space-y-4"><div className="flex flex-wrap justify-between items-center gap-4"><h2 className="font-bold text-lg">Applicant pipeline</h2><Field label="Filter opening"><select value={jobId} onChange={event=>setJobId(event.target.value)}><option value="All">All openings</option>{jobOpenings.map(job=><option key={job.id} value={job.id}>{job.title}</option>)}</select></Field></div><p className="text-xs text-slate-500">Optional AI review sends resume text and the job title to the configured Gemini service. Obtain the applicant's permission before using it. Review suggestions yourself; scores never move applicants automatically.</p>
      <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{(['Applied','Interview','Offered','Rejected'] as const).map(stage=><section key={stage} className="rounded-xl bg-slate-100 dark:bg-slate-900 p-3 space-y-3 min-w-0"><h3 className="text-sm font-bold">{stage}</h3>{candidates.filter(candidate=>candidate.stage===stage && (jobId==='All'||candidate.jobId===jobId)).map(candidate=><article key={candidate.id} className="account-panel !p-4 space-y-3"><div><h4 className="font-semibold">{candidate.name}</h4><p className="text-xs text-slate-500 break-all mt-1">{candidate.email}</p><p className="text-xs text-slate-500">{candidate.jobTitle}</p></div><Field label="Hiring stage"><select value={candidate.stage} onChange={event=>void onUpdateCandidateStage(candidate.id,event.target.value as Candidate['stage'])}>{['Applied','Interview','Offered','Rejected'].map(value=><option key={value}>{value}</option>)}</select></Field>{candidate.resumeText && <details><summary className="text-xs cursor-pointer underline">Resume text</summary><p className="text-xs whitespace-pre-wrap mt-2 max-h-64 overflow-auto">{candidate.resumeText}</p></details>}<button className="text-xs text-indigo-600 underline" disabled={!!evaluating || !candidate.resumeText} onClick={async()=>{setEvaluating(candidate.id);try{await onEvaluateCandidateAI(candidate.id);}finally{setEvaluating('');}}}>{evaluating===candidate.id ? 'Reviewing…' : 'Request AI review'}</button>{candidate.aiEvaluation && <div className="text-xs border-t border-slate-200 dark:border-slate-800 pt-3"><strong>AI suggestion: {candidate.aiScore}/100</strong><p className="whitespace-pre-wrap mt-2">{candidate.aiEvaluation}</p></div>}</article>)}</section>)}</div>
    </section>
  </div>;
}
